### PR TITLE
Scss folder reorganized

### PR DESCRIPTION
**Pull request by jacmoe**
Following the Sass guidelines, and using a modified version of the 7-1 pattern, as described here:
http://sass-guidelin.es/#the-7-1-pattern

### CODE REVIEW

**Comment by samdark** [comment]
Seems to be conflicting/

**Comment by jacmoe** [comment]
Odd - I actually did not mean to push the last two commits - but can't see why it should conflict. :(

**Comment by cebe** [comment]
I'll merge it, conflict is easy to resolve

**Comment by jacmoe** [comment]
I actually managed to see the conflict - am proud of myself :)
Thanks @cebe !

You saved me from yet again resetting my repository :p

**Comment by cebe** [comment]
btw, there seems to be a scss error:

```
Error in plugin 'sass'
Message:
    scss/1-common/_colors.scss
Error: Undefined variable: "$brand-success".
        on line 6 of scss/1-common/_colors.scss
>>     color: $brand-success;
   -----------^
```

**Comment by jacmoe** [comment]
D'oh - I will fix

**Pull request merged**
