### PR TITLE
add indent to social login block

### PR DESCRIPTION
**Pull request by Arhell**
[issue](https://github.com/yiisoft-contrib/yiiframework.com/issues/206)

### CODE REVIEW

**Comment by samdark** [comment]
That's creative but not what I've meant in the issue. I've meant actual vector graphics that is able to scale and not PNG wrapped into SVG.

**Comment by Arhell** [comment]
Got it, don't close PR please, I'll see what can be done

**Comment by Arhell** [comment]
I renewed PR and issue
[issue](https://github.com/yiisoft-contrib/yiiframework.com/issues/206)

1. Already fixed
2. Added more indentation on the mobile screen

**Comment by samdark** [comment]
Merged/deployed. Thanks1

**Pull request merged**
