### PR TITLE
Guide Header Menu

### PR DESCRIPTION
**Pull request by agungsijawir**
See #159

### CODE REVIEW

**Comment by rob006** [comment]
You can fix this with

```css
.btn-group-justified > .btn-group:last-child .dropdown-menu {
    right: 0;
}
```

Much easier and no need to use tiny font for dropdowns.

**Comment by jacmoe** [comment]
This is not acceptable because the design is not true to the design made by
Eshill.
If I were on my machine instead of my phone I would link to the design
dokument.
@eshill

**Comment by jacmoe** [comment]
Because the menu dropdown should span the parent, which is tricky...

**Comment by jacmoe** [comment]
Try and search the closed issues / tickets for "mock" to see the design.

**Comment by agungsijawir** [comment]
@jacmoe what are you referring to? me or @rob006?

**Comment by agungsijawir** [comment]
ah, so you refer to this comment, @jacmoe ?
https://github.com/yiisoft-contrib/yiiframework.com/issues/94#issuecomment-165054275

**Comment by agungsijawir** [comment]
trying use suggestion from @rob006, will try to another PR.

**Pull request closed without merging**
