### PR TITLE
Split status page by version, add issues & pulls numbers

### PR DESCRIPTION
**Pull request by machour**
- Added version selection to the status page (default to 2.0)
- Added number of open issues & pull requests for each repo
- Updated Yii 3 repositories list

Screen Shot 2019-05-12 at 2 15 36 PM

### CODE REVIEW

**Comment by samdark** [comment]
I wonder if it is possible to add a number of issues fixed in master since last release. That would be super-useful.

**Comment by machour** [comment]
@samdark Added number of PRs (max 10) merged after last release date.
PRs seems to be a better metric as issues can be questions, duplicates, etc.

The link's title display the PRs recap, and a click lands you on the CHANGELOG.

Screen Shot 2019-05-12 at 5 34 08 PM

Enjoy!

**Comment by samdark** [comment]
Cool!

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
