### PR TITLE
Download page

### PR DESCRIPTION
**Pull request by johonunu**
Design implementation of "download" page is completed.

### CODE REVIEW

**Comment by jacmoe** [comment]
Nice work :+1:  Thanks!

**Comment by cebe** [comment]
@johonunu @eshill What is the source of the flags? Currently the download page is missing flags for French and Polish also later other languages may be added.

**Comment by cebe** [comment]
found it in another issue: http://www.softicons.com/web-icons/flags-flat-icons-by-gosquared

**Comment by johonunu** [comment]
@cebe, I have just cropped them from the design @eshill provided, don't know where he got them:
https://github.com/eshill/yiiframework.com/blob/master/png/download.png

**Comment by eshill** [comment]
[Flags_png.zip](https://github.com/yiisoft-contrib/yiiframework.com/files/432411/Flags_png.zip)

**Pull request merged**
