### PR TITLE
Tightening up the theme - stage 2 (of 3)

### PR DESCRIPTION
**Pull request by jacmoe**
I have now fixed the theme and applied Josefin and Roboto fonts and fixed the navbar up.
The footer has been fixed properly at the bottom and I think I am ready to fix up the rest of the index page.
That will probably be in stage 3 where the site is ready to be taken to the next step which is incrementally improving upon content and minor stylistic issues.

### CODE REVIEW

**Comment by jacmoe** [comment]
I have applied the Tenby Five font to all headers. Let us see if we like it. I think it looks great.

**Comment by jacmoe** [comment]
The real reason for these changes is really to clean up and reorganize the underlying css so that it becomes easier to tweak the site to our likings.
It has to be done :p

**Comment by cebe** [comment]
So should I merge it?

**Comment by jacmoe** [comment]
That would be great - before it gets too big :)
Den 26/11/2015 09.52 skrev "Carsten Brandt" <notifications@github.com>:

**Pull request merged**
