### PR TITLE
Resolved https://github.com/yiisoft/yii2/issues/17439

### PR DESCRIPTION
**Pull request by hirenbhut93**
Resolved https://github.com/yiisoft/yii2/issues/17439

### CODE REVIEW

**Comment by samdark** [comment]
Duplicate of #

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by rob006** [comment]
This change is incorrect, names are intentionally switched to confuse bots: https://github.com/yiisoft-contrib/yiiframework.com/commit/67cf3df7aa685541cc0a06d7976cfed90fecf7dc#diff-2543704f65149bc0b2265ab779281eac

Right now "your name" field expects email address and "your email" accepts anything.

e182d547
1dab3897

**Comment by samdark** [comment]
Reverted :) @cebe that's rather confusing way. Are you sure it's confusing for bots as well?

**Pull request merged**
