### PR TITLE
Enhance web site accessibility

### PR DESCRIPTION
**Pull request by machour**
Using lighthouse, this PR starts at a 47% score

screen shot 2019-02-23 at 6 44 58 pm

I'm currently focusing on the contrast issue. This will require some visual changes, like for the footer:

| before | after |
|------|----|
| screen shot 2019-02-23 at 7 03 29 pm | screen shot 2019-02-23 at 7 03 01 pm |

### CODE REVIEW

**Comment by cebe** [comment]
Good changes!

**Comment by machour** [comment]
@cebe @samdark my work here is done, all pages are now 100% accessible and way easier on the eyes.

As accessibility is also a matter of items placement & separation, I allowed myself the following visual changes:

| before | after |
|-------|-------|
|Screen Shot 2019-03-23 at 2 06 13 PM|Screen Shot 2019-03-23 at 2 09 59 PM|

Date is under the title, making it clear to what item it belong to. Same goes with comments.
Counts without `()` and aligned to the right.

Also aligned extensions & news based on that.

**Comment by machour** [comment]
Forgot to mention, I had to change the "Secure" logo to use a color with more contrasts.
Used our logo's green

| before | after |
|--|--|
|Screen Shot 2019-03-23 at 2 13 50 PM|Screen Shot 2019-03-23 at 2 13 55 PM|

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
