### PR TITLE
Polish flag

### PR DESCRIPTION
**Pull request by bizley**
Better colours

### CODE REVIEW

**Comment by rob006** [comment]
@cebe This should be reverted - previous flag has the correct colors ( https://en.wikipedia.org/wiki/Flag_of_Poland#Shades_of_red ).

**Comment by cebe** [comment]
Is the upper part really grey? I do not see that in the wiki article.

**Comment by bizley** [comment]
It is more silverish in official docs but these are intended for fabrics. There is no official colour representation for monitor displays at the moment. The silver-like colour looks white on black background and gray an white background and that is why my proposition is to use white version which is popular among the internet.

**Comment by rob006** [comment]
> Is the upper part really grey? I do not see that in the wiki article.

Yes, officially it should be `#E9E8E7`. It is described more clearly on Polish wiki: https://pl.wikipedia.org/wiki/Flaga_Polski#Odcie.C5.84_bieli_na_polskiej_fladze

**Comment by bizley** [comment]
Yup, this is RGB convertion from the act text but the act does not acknowledge LCD displays and it doesn't look good, especially on the white background and next to flag of Japan. I will attach another approach if you persist the silver one.
pl-flag-nonwhite

**Comment by rob006** [comment]
Real issue is the shade of red - current one looks like pink... I'm fine with pure white, but this red part looks ugly.

**Comment by bizley** [comment]
It's `#D4213D` like in the act and Wiki.

**Comment by rob006** [comment]
They differ:

pl-flag

**Comment by bizley** [comment]
You are right, my bad. I've made another PR with `#ffffff` and `#d4213d`.
See #152

**Pull request merged**
