### PR TITLE
login and signup pages

### PR DESCRIPTION
**Pull request by johonunu**
I was working on login and signup pages. @jacmoe can you check this out?
Bare in mind, this is the first time I use sass ;)

### CODE REVIEW

**Comment by johonunu** [comment]
I didn't use github icon from the design, because that icon is not available in fontawsome.

login

**Comment by jacmoe** [comment]
Looks great :)

What do you mean by 'it's not available in FontAwesome' ?

Set the colour to white for the i tag or font.

Or, if you want to be fancy, use stacked FontAwesome icons.

I think I will hold off accepting this PR until you fixed it :)

Because I know that our designer will not be happy about the icon.

Otherwise: awesome work :+1:

**Comment by jacmoe** [comment]
Alternatively, you can let me fix it - but I'll give you the chance first.

**Comment by jacmoe** [comment]
I am using the FA font for the social icons in the footer - so check that out.
I probably should use stacked icons, will change to using that later, but it should give you a hint about how to make that octopus white.

**Comment by johonunu** [comment]
I will look into it later today ;)

**Comment by johonunu** [comment]
I think icon is fine now. You can merge it and modify the code, I don't mind ;)

fixed

**Comment by jacmoe** [comment]
Thanks a lot! :+1:

**Pull request merged**
