### PR TITLE
WIP News section

### PR DESCRIPTION
**Pull request by cebe**
started working on the news section, issue #47

open todos:

- [x] complete admin part
- [x] make sure slugs work as expected
- [x] tags
- [x] news sidebar: related news
- [ ] ~~news search~~
- [x] import for data from current site

### CODE REVIEW

**Comment by cebe** [comment]
some new on the old site have images attached, do we want this here too?

**Comment by samdark** [comment]
I don't think we need that from the very start and not sure we'll need that ever.

**Comment by samdark** [comment]
It may be handy to be able to upload images and then later reference them via markdown though.

**Comment by samdark** [comment]
So in form of `image_id` it looks pretty useless to me.

**Comment by cebe** [comment]
News section is ready! :)

**Pull request merged**
