### PR TITLE
min images books folder

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/yiisoft-contrib/yiiframework.com/issues/629

### CODE REVIEW

**Comment by samdark** [comment]
@Arhell the compression added significant artifacts.

**Comment by Arhell** [comment]
@samdark 
Decreased by 11%
I compared, it seems normal

**Comment by samdark** [comment]
Well, there are additional artifacts but not as bad as in the first try. Let's merge it.

**Comment by Arhell** [comment]
Yeah thanks
Then I'll refine it a little more so that it is compressed and without strong artifacts, I will do it as best as possible

**Pull request merged**
