### PR TITLE
Keep only one h1 tag per page

### PR DESCRIPTION
**Pull request by rob006**

### CODE REVIEW

**Comment by jacmoe** [comment]
I totally agree.
Perhaps I am guilty of that as well as a short-cut to easy styling.
Consisten header use is important for the proper Google mumbo to work.

**Comment by cebe** [comment]
same issue exists on guide index page: https://github.com/yiisoft-contrib/yiiframework.com/blob/master/views/guide/index.php#L15 I see some duplicated code here, could be moved to a partial...

**Comment by rob006** [comment]
@cebe In guide index there is no second h1 header, so this is fine.

**Comment by cebe** [comment]
I right :)

**Pull request merged**
