### PR TITLE
Added proper set of favicons

### PR DESCRIPTION
**Pull request by jacmoe**
Set of favicons for Apple, Android, Windows Phone, etc..
Generated from large icon fetched from the eps

### CODE REVIEW

**Comment by jacmoe** [comment]
I tried to put the icons in a 'icons' directory but I think that's how favicons doesn't work.. ;)

**Comment by samdark** [comment]
Thanks!

**Comment by cebe** [comment]
> I tried to put the icons in a 'icons' directory but I think that's how favicons doesn't work.. ;)

if the url is specified in the HTML header you can put them in subdir without any problem afaik.

**Comment by jacmoe** [comment]
> if the url is specified in the HTML header you can put them in subdir without any problem afaik.
I will put that on a todo.

**Comment by samdark** [comment]
Wrong. Some browsers are still getting these from root even if there's an URL.

**Comment by jacmoe** [comment]
From what I've heard they try to fetch automatically from the root as an
optimization before loading the actual page.

2015-11-22 22:23 GMT+01:00 Alexander Makarov <notifications@github.com>:

**Comment by samdark** [comment]
Yes.

**Comment by cebe** [comment]
but only favicon.ico, not the other icons afaik. Or what are you talking about?

**Comment by samdark** [comment]
Others as well.

**Comment by rob006** [comment]
> Some browsers are still getting these from root even if there's an URL.

AFAIK this only applies to the `apple-*` icons. 
We can put favicons in subdirectory and create some redirections for browsers that ignore declarations in HTML head.

**Comment by samdark** [comment]
Not only `apple-*`. I don't see any point of moving icons...

**Comment by jacmoe** [comment]
It is only going to complicate things. KISS FTW. :)

2015-11-22 23:20 GMT+01:00 Alexander Makarov <notifications@github.com>:

**Comment by rob006** [comment]
I've never seen request for other icons (except favicon.ico) for websites, which have declared icons urls in head.
Webroot without over 20 files will look more clear. Right now on first look it's real mess, it's hard to find other files between icons.

**Comment by jacmoe** [comment]
People are increasingly using mobile devices to browse the web, and I don't think that a couple of icons in the web root hurts anyone.
It is important to me that there is beautiful Yii icons on iPad, iPhone, Windows Phone, Android, .. whatever.
Back in the old days, all you needed was a favicon.ico..

**Comment by samdark** [comment]
http://realfavicongenerator.net/

**Comment by jacmoe** [comment]
That one looks really nice!

I used this, btw: http://www.favicon-generator.org/

2015-11-23 0:10 GMT+01:00 Alexander Makarov <notifications@github.com>:

**Comment by rob006** [comment]
I'm not talking about removing these icons, just moving it into other directory and add fallback for request for icons in webroot. You have then one additional rewrite rule in .htaccess (or one additional route in config and simple controller for redirections), over 20 files less in webroot and all icons works fine. I'm not sure if it is complicated that much.

**Comment by samdark** [comment]
@rob006 what for?

**Comment by rob006** [comment]
For the same reason why css and js files are not in webroot - it's look cleaner and it's easier to read. 
But it's just a suggestion - it is not really important thing...

**Pull request merged**
