### PR TITLE
Use fonts from googlefonts

### PR DESCRIPTION
**Pull request by rob006**

### CODE REVIEW

**Comment by jacmoe** [comment]
I don't want to use their shitty fonts because it slows the site down tremondously.
Why do you think I bothered to create a webfont package for it at Fontsquirrel?
I don't want the site to have a Google font white-out.
If you have arguments for the opposite, they better be good :)

**Comment by rob006** [comment]
This also changes header font from

969160e75907139a952d5c0766ef

to 

90c3d5011ee917e935a3745882de

I can fix it, but I think that new version looks better.

**Comment by jacmoe** [comment]
We can't change the looks without consulting out designer @eshill first.

Google fonts are blocked by China, so I don't think it is a good idea.
That is in addition to the hit on the performance of the site.

**Comment by jacmoe** [comment]
Notice that I changed it *from* Google fonts to local webfonts, so sharpen your pencils :)

**Comment by jacmoe** [comment]
This is not acceptable. Sorry :)
We just decided to use Source Code Pro for the highlighting.
And it is only a day or two ago since I pushed the PT sans fonts because they are used for the new design.
Check it out at https://github.com/eshill/yiiframework.com
If you have Photoshop, please tell me the exact font he is using for what because The Gimp does not have that kind of freedom with PSD files :)

**Comment by rob006** [comment]
I changed it because I hate Fontsquirrel font family declarations like pt_sansregular and it was really annoying when I start playing with guide header. Googlefonts is the simplest way to make it work and up to date. If we don't want googlefont we can use bower to manage fonts.

**Comment by jacmoe** [comment]
We can change the name in the scss, no problem :)
I think I hate Google fonts as much as you have funky Fontsquirrel names :p

It was only yesterday that we decided to apply the Source code pro font - please see this:
https://github.com/yiisoft-contrib/yiiframework.com/issues/94#issuecomment-165714020

**Comment by jacmoe** [comment]
Btw, since we are using Sass, why not just create a variable to cut down on the writing?
~~~
$h-font: 'long-font-name-that-i-dont-want-to-write-every-goddamn-time;
~~~

**Comment by rob006** [comment]
This PR uses Source Code Pro.

The problem is not only name - right now you must handle font updates by yourself. Putting fonts into scss directory also mess with search results, when you try to find something in styles declarations.
The problem with name is not that because it is long or ugly, but because it handling font-weight not by `font-weight` css property - it uses font family to trick browser (and coder) and display bolded font even if it has `font-weight: normal;`.

**Comment by jacmoe** [comment]
FYI: the font families are currently defined in `scss/2-vendors/_bootstrap-variables.scss` - it is acceptable to create shorthand names for them there, in addition to what's already written:
~~~
$font-family-sans-serif: 'pt_sansregular', sans-serif;
$font-family-base: $font-family-sans-serif;
$font-family-monospace:   'source_code_proregular', monospace;

$bold-headings-font-family: 'pt_sansbold', sans-serif;
~~~
I would prefer that we kept the font famlies there in the unlikely event that we decided to change them in the future.

**Comment by jacmoe** [comment]
> The problem is not only name - right now you must handle font updates by yourself.

I mean, how often do fonts update?
I bet we would have to update Bootstrap several times over before we would have to update the PT sans or SCP fonts.

We are not using the bold version of Source code pro because it makes the code stand out too much.

**Comment by rob006** [comment]
@jacmoe I have modified this declarations in this PR, so I now about them :)

**Comment by jacmoe** [comment]
Some font licences require that you change the name of the font when using
a derived version, so it would be advised to check the respective licenses
first before doing any changes to the names that we use for them.

**Comment by jacmoe** [comment]
Then I don't understand the argument against funky font names, because the
variables there are supposed to be used in the other sass files.
If we didn't, then we could just as well use plain CSS.
Den 19/12/2015 16.22 skrev "Robert Korulczyk" <notifications@github.com>:

**Comment by rob006** [comment]
cdaea9846308d0e76812d94d3a68

Text is bold even if in CSS has `font-weight: normal;`.

**Comment by jacmoe** [comment]
Now that we do have a mock, I would rather have that we concentrate on how
to best honor the design that has been provided.
We can worry about nitpick later I think. :)

**Comment by jacmoe** [comment]
Yes that font is indeed bolder because the font is different from the PT
Sans Regular used elsewhere.
Simply because Sergei used that font for those headings and not the rest of
the headings.
PT Sans Bold, I think.
There are differences between them, unless I am totally mistaken.
Some fonts does not differ..

**Comment by jacmoe** [comment]
I will ask him if it is a separate font.

**Comment by jacmoe** [comment]
Wait a minute - the change you made would mean that we would have to
download not three, but at least 7 fonts from Google.
That is not really an improvement. Each weight and variant means a separate
font.
That can't be what you had in mind?

**Comment by rob006** [comment]
Just look how google font-face declarations looks:

https://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic|Source+Code+Pro&subset=latin,cyrillic,latin-ext

They don't use different font-family for every font variation, so if you want make some text bold, you just use `font-weight: bold` and don't change font-family - it is much more clear than hack all font styles by changing `font-family`. 
They also uses `src: local()` so if user already have this font installed, he does not have to download it again.

**Comment by jacmoe** [comment]
The weight meter for that must be huge +1

**Comment by rob006** [comment]
Browsers download only these font, which is needed. So if there will be no italic text on page, no italic font will be downloaded.

**Pull request closed without merging**
