### PR TITLE
fix link is out of scope

### PR DESCRIPTION
**Pull request by Arhell**
[issue](https://github.com/yiisoft-contrib/yiiframework.com/issues/472)

### CODE REVIEW

**Comment by samdark** [comment]
👍

**Comment by rob006** [comment]
This looks like hotfix for this specific issue. But in general there is nothing special in 767px width and active links - you can have long URL that is not a link and it will overflow on wider screens than 767px.

**Comment by samdark** [comment]
Well, yeah. Constraint could be removed.

**Comment by Arhell** [comment]
@rob006 tnxs
it makes sense, tidy up in the next PR

**Pull request merged**
