### PR TITLE
Contribute page

### PR DESCRIPTION
**Pull request by johonunu**
#94 Contribute page done :) 
Also, I fixed the wrong paths of icons used in blockquotes(currently not showing due to wrong path):
http://yiiframework.domain-na.me/doc/guide/2.0/en/start-installation

### CODE REVIEW

**Comment by jacmoe** [comment]
Really, really appreciated!

**Comment by johonunu** [comment]
No problem :+1:

**Comment by cebe** [comment]
Thank you! updated the site: http://yiiframework.domain-na.me/contribute

**Comment by samdark** [comment]
Ohh! Thanks!

**Pull request merged**
