### PR TITLE
Tightened up the theme a bit

### PR DESCRIPTION
**Pull request by jacmoe**
applied Bootstrap theme.

### CODE REVIEW

**Comment by samdark** [comment]
Probably worth removing stuff instead of commenting out?

**Comment by jacmoe** [comment]
It is, under normal circumstances but I am not sure what can be safely removed and what can't.
There is a lot of stuff in Roxie that is either not used or a duplicate of what Bootstrap already does.
I will definitely remove it all when I am totally sure that it doesn't do something useful. It is WIP.

**Comment by jacmoe** [comment]
The stuff in boostrap_variables is meant to be commented out - it's there to show the list of things that can be overridden.

**Comment by jacmoe** [comment]
@samdark : I think it would be a good idea to either merge or decline at this point :)

I am not too happy about the brands section in the topnav but I think I managed to fix the funkiness.
Now the topbar and navbar behaves properly in various screen resolutions.

The next step is to work on the guide/api and that is an unrelated piece of work.
So if you want to merge this, then we won't have a huge pile of changes crammed into one gigantic PR. :p

**Comment by samdark** [comment]
Merged.

**Comment by jacmoe** [comment]
Thanks :)

**Pull request merged**
