### PR TITLE
add amazing dropdown menu animation

### PR DESCRIPTION
**Pull request by hscstudio**

### CODE REVIEW

**Comment by cebe** [comment]
for me it is working on all the dropdowns but it is shaking the dropdown around which is pretty annoying imo. I can only start reading the available options when the animation is over.
For a menu functionality has the highest priority, so fancy animations should not disturb the usage.

**Comment by samdark** [comment]
Agree. In this case no animation is better.

**Comment by cebe** [comment]
There could be an animation but it should not be disturbing the usage. By disturbing I mean mostly not delay the navigation.

**Comment by hscstudio** [comment]
I just wanted to give the different impression to the visitor, but this did not disturb, the animation may be made softer and not for all but the main menu dropdown only

**Comment by cebe** [comment]
@hscstudio feel free to adjust the animation.

**Pull request closed without merging**
