### PR TITLE
Updated gulp config

### PR DESCRIPTION
**Pull request by asamats**
I don't know about you but I can't build with old gulp config that is why I updated gulp config.

### CODE REVIEW

**Comment by machour** [comment]
Hi @asamats, the website is build with current config, and I'm able to do it too, using node 4.9.1

The node version limitation is caused by a wrong callback usage in `gulp-touch`, swapping this package for `gulp-touch-cmd` seems to be fixing this problem.

That being said, I'm all for refreshing our build that looks a bit dusty, but @cebe will make the final decision as the website is hosted in his stack, with his own maintenance constraints.

Here's what I get when running your PR locally with two different node versions:

```
🍺  ~/oss/yiisoft-contrib/yiiframework.com (master)*$ nvm use 4.9.1
Now using node v4.9.1 (npm v2.15.11)

🍺  ~/oss/yiisoft-contrib/yiiframework.com (master)*$ gulp
/Users/didou/oss/yiisoft-contrib/yiiframework.com/gulpfile.js:19
let sassOptions = {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

```
🍺  ~/oss/yiisoft-contrib/yiiframework.com (master)*$ nvm use system
Now using system version of node: v11.3.0 (npm v6.4.1)

🍺  ~/oss/yiisoft-contrib/yiiframework.com (master)*$ gulp
[13:52:57] Using gulpfile ~/oss/yiisoft-contrib/yiiframework.com/gulpfile.js
[13:52:57] Starting 'default'...
[13:52:57] Starting 'build'...
[13:52:57] Starting 'clean'...
[13:52:57] Finished 'clean' after 14 ms
[13:52:57] Starting 'sprites'...
[13:52:58] Finished 'sprites' after 1.05 s
[13:52:58] Starting 'styles'...
[13:52:58] Starting 'forumheader'...
[13:52:58] Starting 'scripts'...
[13:52:58] Starting 'fonts'...
[13:52:59] gulp-notify: [Gulp notification] Forum Header Styles task complete
[13:52:59] Finished 'forumheader' after 315 ms
[13:53:05] gulp-notify: [Gulp notification] Scripts task complete
[13:53:05] Finished 'scripts' after 6.33 s
[13:53:05] gulp-notify: [Gulp notification] Styles task complete
[13:53:05] Finished 'styles' after 6.34 s
[13:53:05] Finished 'fonts' after 6.35 s
[13:53:05] Finished 'build' after 7.54 s
[13:53:05] Starting 'watch'...
[13:53:05] 'watch' errored after 60 ms
[13:53:05] Error: watching assets/src/scss/**/*.scss: watch task has to be a function (optionally generated by using gulp.parallel or gulp.series)
    at Gulp.watch (/Users/didou/oss/yiisoft-contrib/yiiframework.com/node_modules/gulp/index.js:28:11)
    at /Users/didou/oss/yiisoft-contrib/yiiframework.com/gulpfile.js:83:8
    at taskWrapper (/Users/didou/oss/yiisoft-contrib/yiiframework.com/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/didou/oss/yiisoft-contrib/yiiframework.com/node_modules/async-done/index.js:55:18)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
[13:53:05] 'default' errored after 7.6 s
```

Also, when switching the config from `yaml` to `json`, we loose the ability to have comments in that file. Maybe a `.js` with an export could be better here.

**Comment by asamats** [comment]
Hi @machour, Thank you for the report! Yes, you right all about you said. I'll fix all of the bug and notes.

**Comment by asamats** [comment]
OMG, I broke this pull-request. Excuse. I'll reopen.

**Comment by machour** [comment]
no worries 😅 

so I guess you're also working on #392 ?

**Comment by asamats** [comment]
Yes, I did and know it's done)

**Pull request closed without merging**
